### ISSUE TITLE
Discourse API Read Only Key

### ISSUE THREAD

**Issue by SirAh0** [smartcontractresearchforum/IT#136]
### How to Generate API Key
1. Navigate to [admin / api page](https://www.smartcontractresearch.org/admin/api/keys/new)

Description: `API - All Users Read Only`
User Level: `All Users`
Scope: `Read Only`

2. Copy the generated key and send it to @SirAh0 via direct message.

**Comment by eleventh19** [comment]
Did the above and shared the key with @SirAh0
