### ISSUE TITLE
Need Onboarding Folder in SCRF Drive🗄️ - Drive

### ISSUE THREAD

**Issue by vincenzospaghetti** [smartcontractresearchforum/IT#30]
### Issue Text

@SirAh0 needs an Onboarding Folder in SCRF Drive

![image](https://user-images.githubusercontent.com/93289575/175975075-bc1468f0-c28d-4c0f-9ece-6e817b40277c.png)

**Comment by vincenzospaghetti** [comment]
@zubepaul - may have a larger conversation here about drive organization

**Comment by SirAh0** [comment]
There is an Onboarding Folder inside Engagement. The share settings are in place. Let me know if you need any further help!

https://drive.google.com/drive/folders/1uAF9-FI7pGQOHpgqqr-55c0_0XCKs1ga?usp=sharing

**Comment by SirAh0** [comment]
> Onboarding Google Team is embedded in Engagement. Does there need to be an onboarding group if there are various level of engagement teams?

We can have sub-folders with specific rights with as many groups as needed. So if someone needs special access to an onboarding folder we can create groups for that.

**Comment by SirAh0** [comment]
For reference here is the public onboarding folder

https://drive.google.com/drive/folders/1xaQMA3hxpGFsNSURvrCfbhrmYgSjl0DH?usp=sharing

**Comment by SirAh0** [comment]
> 

I added the work@ group to the onboarding folder so they can add and edit files there. Anyone with an @scrf.io email is part of the work@ group.

**Comment by zubepaul** [comment]
That should work for the moment.

**Comment by SirAh0** [comment]
Cool going to close this issue.
