### ISSUE TITLE
💾 - Project Board

### ISSUE THREAD

**Issue by twan-dev** [smartcontractresearchforum/IT#5]
### Issue Text

engagement project board changes please. Details are specified in the DM between us!

**Comment by SirAh0** [comment]
### Issue Templates
contributors to create bounties
examples:
[bounty: Forum Expert Cryptography](https://github.com/smartcontractresearchforum/.github/issues/1)
[bouny: Privacy Notable Works](https://github.com/smartcontractresearchforum/engagement/issues/23)

Having lots of issue templates is not a problem! Create a markdown file in the repo as a sort of menu, a guide, a curated view of issue templates and other information. You can have as many issue templates as you want! 


### Automation
**Event** New Issue
**Target** Any issue from template
**Actions** 
add to [engagement board]([https://github.com/orgs/smartcontractresearchforum/projects/32](https://github.com/orgs/smartcontractresearchforum/projects/32/views/1))
status: new
label: [TBD]
Meta Data : TBD (TODO: this can be set by issue templates)  @SirAh0 @twan-dev 

**Event** Issue Update
**Event Filter**
Issue type: [Content Pipeline]([https://github.com/orgs/smartcontractresearchforum/projects/5](https://github.com/orgs/smartcontractresearchforum/projects/5#column-13896115)) pb
status change to: `engagement and calendaring`

**Comment by SirAh0** [comment]
Do you have a preference on who should be assigned on new issue creation?

**Comment by SirAh0** [comment]
Issue Template added `🎯 - New Bounty`
https://github.com/smartcontractresearchforum/engagement/issues/new/choose

**Comment by SirAh0** [comment]
Automation complete

**Comment by SirAh0** [comment]
For further automation on these boards please open a new ticket
