### ISSUE TITLE
🧰 - General- If statement for emoji automations

### ISSUE THREAD

**Issue by twan-dev** [smartcontractresearchforum/IT#50]
### General Issue

Just getting curious, we are managing & limiting emojis because the function for automation uses a more general if statement 
```
if contains "this emoji":
    add to project board/do this automation
```

 Is it possible to have a more specific if statement?
```
if first character is "this emoji"                           // if string starts with "this emoji"
    add to project board/do this automation
```

**Comment by SirAh0** [comment]
yes, we can do that. Can also make use of surrounding characters to act as a tag like this: [🧰] 

Then after the [🧰] any number of emojis can be used. 

The basic idea though is that that is a 1-1 mapping of emojis to a category of Issue.
