### ISSUE TITLE
🧰 - General - Regular Contributor Badge

### ISSUE THREAD

**Issue by twan-dev** [smartcontractresearchforum/IT#52]
### General Issue

(This needs to be project-planned and coordinated with engagement&&discovery before we get it launched or anything. It's just a technical question at this point)

Question:

What are the technical barriers or recommended practices to creating a custom badge (probably on our forum), which we give out to people that have **_published at least 1 summary every month_** from the content pipeline **_consecutively on a streak_**?

This could be something that shows up in the lower right corner of their profile (like how the  "research team" badge currently does), but updates based on how many months they have published a research summary (or any other type of content from the content pipeline), there should be a color or number update.

**Comment by SirAh0** [comment]
Discourse uses a Badge system which looks like we can add our own badges to.

https://meta.discourse.org/t/what-are-badges/32540

Happy to do a tour with you on this feature and see what is possible.

Here is something cool to consider, we can use the API to assign custom badges. 
https://meta.discourse.org/t/how-to-grant-a-custom-badge-through-the-api/103270

So for example, if someone completed a certain Issue (from an Issue Template) the action could result in that API being called and badge automatically assigned.

**Comment by twan-dev** [comment]
That sounds like good info. Thanks for the mini research on this topic.
