### ISSUE TITLE
🧰 - General - external sharing options for primary calendars

### ISSUE THREAD

**Issue by twan-dev** [smartcontractresearchforum/IT#60]
### General Issue

I wonder if access could be bumped up from "only free/busy info (hide events details)" to "share all info and outsiders can change calendars"?

(admin > google workspace > calendar > sharing settings > external sharing options for primary calendars)

I hope this makes it easier to work with & for people that don't use their scrf.io email as a primary calendar.

**Comment by SirAh0** [comment]
![image](https://user-images.githubusercontent.com/12703396/179558246-107fd994-75cd-4927-9c63-a92c36a6812e.png)
