### ISSUE TITLE
🧰 - General - Calendar external invitations

### ISSUE THREAD

**Issue by twan-dev** [smartcontractresearchforum/IT#61]
### General Issue

Can we uncheck "warn users when inviting guests outside of the domain"? 

Meetings with external contributors come from time to time and post little threat to the security of our workspace.

(admin > google workspace > calendar > sharing settings > external invitations)

**Comment by SirAh0** [comment]
![image](https://user-images.githubusercontent.com/12703396/179558406-eef70e2f-f0ed-4a7c-8e63-d740e39d026a.png)
