### ISSUE TITLE
🧰 - General - Google Docs sharing warning

### ISSUE THREAD

**Issue by twan-dev** [smartcontractresearchforum/IT#62]
### General Issue

Can we uncheck "For files owned by users in (our org) warn when sharing outside of (our org)"? 

Collaboration with external contributors come from time to time and post little threat to the security of our workspace.

(admin > google workspace > drive and docs > sharing settings > sharing options > sharing outside of (our org))

**Comment by SirAh0** [comment]
![image](https://user-images.githubusercontent.com/12703396/179559848-c4d06836-fd36-450a-bd6d-10e6ebcfada7.png)
