### ISSUE TITLE
🧰 - Google Analytics on Forum

### ISSUE THREAD

**Issue by SirAh0** [smartcontractresearchforum/IT#69]
### General Issue

@marvino3 
Wants to know if we can get analytics on our forum.

**Comment by marvino3** [comment]
@SirAh0 we just had an issue where we were trying to determine where forum users were coming from (aka source) and if they are viewing content on the phone vs web for user journey purposes. 

We are realizing being able to view these analytics is becoming critical

**Comment by SirAh0** [comment]
This should be live now!
