### ISSUE TITLE
💾 - Umar - Open Peer Review PB

### ISSUE THREAD

**Issue by twan-dev** [smartcontractresearchforum/IT#7]
### Issue Text

Umar needs access to the open peer review board

**Comment by twan-dev** [comment]
#8 Creating a team for them would also work

**Comment by SirAh0** [comment]
what is Umar's Github username?

**Comment by SirAh0** [comment]
User ufkhan97 has been invited to the Org and Peer Review Team, see ticket

https://github.com/smartcontractresearchforum/IT/issues/8
