### ISSUE TITLE
🧰 - General - Typo Edits

### ISSUE THREAD

**Issue by twan-dev** [smartcontractresearchforum/IT#77]
### General Issue

May I have access to edit-out the metadata that was not supposed to show up on the top of the post? 
https://www.smartcontractresearch.org/t/research-summary-studying-bitcoin-privacy-attacks-and-their-impact-on-bitcoin-based-identity-methods/1790

**Comment by SirAh0** [comment]
lets discuss this in our chat tomorrow

**Comment by SirAh0** [comment]
Circling back on this one - do you need further help?

**Comment by twan-dev** [comment]
I got access. Can close this one out. Thanks for checking.
