### ISSUE TITLE
💾 - Teams

### ISSUE THREAD

**Issue by twan-dev** [smartcontractresearchforum/IT#8]
### Issue Text

open peer review team:

1. under eugene
2. team members:
nicklinck
isss111
ewvanwinkle
ufkhan97
3. This team gets access to the open peer review project board

**Comment by SirAh0** [comment]
All users have been invited to the Org and [Open Peer Review](https://github.com/orgs/smartcontractresearchforum/teams/open-peer-review/members) team

@eleventh19 is a maintainer for the team.

The team has write access for the [Open Peer Review Project](https://github.com/orgs/smartcontractresearchforum/projects/27/views/1) PB
