### ISSUE TITLE
🧰 - General - Forum Calendaring Topic

### ISSUE THREAD

**Issue by twan-dev** [smartcontractresearchforum/IT#84]
### General Issue

Implement calendaring function on the forum.

### Description

1. Set up a private category (only visible internally, or by people with certain roles)
2. Have a team on the forum that has access to post to the private category
3. Have a role that has access to "modify the owner of a post"

#### Related links:
- Message I dropped in [internal chat](https://discord.com/channels/784234332617048065/808433290629480540/1007179066396397620)
- [Discourse documentation](https://meta.discourse.org/t/how-to-create-a-timed-topic/60731)

#### Possible first summary to test out
- smartcontractresearchforum/research_content#282

**Comment by SirAh0** [comment]
**Groups**
[Content](https://www.smartcontractresearch.org/g/Content)
Manages staged content

[Contributor](https://www.smartcontractresearch.org/g/Contributor)
Submits staged content

**Category**
[Content Staging](https://www.smartcontractresearch.org/c/content-staging/27)
This is a private category only visible to the above two groups. 

The Content group can moderate posts within the Content Staging category
![image](https://user-images.githubusercontent.com/12703396/184664783-2489c539-b63c-4dd3-90b9-112315ac2b19.png)

All submissions require moderator approval
![image](https://user-images.githubusercontent.com/12703396/184664880-28b97652-fbba-4e69-90b7-44a869b34552.png)

**Comment by SirAh0** [comment]
Once a user has the Contributor role they can post in the Content Staging category pending moderator approval. 

Once the post is approved it can be assigned a publish date and moved to the appropriate category per the [Discourse documentation](https://meta.discourse.org/t/how-to-create-a-timed-topic/60731).

**Follow Up**
- [ ]  Tolu needs to be able to transfer post ownership

**Comment by SirAh0** [comment]
All members of the [Content team](https://www.smartcontractresearch.org/g/Content) are moderators for the private category [Content Staging](https://www.smartcontractresearch.org/c/content-staging/).

Once a post is ready for publication, any member of the Content group can schedule the publication and transfer post ownership to the Discourse user account that belongs to the author of the content. 

Feel free to direct any member of the Content team my way if they need any help.

**Comment by twan-dev** [comment]
It seems that we are not moderators yet
![Screen Shot ](https://user-images.githubusercontent.com/85469891/184877421-2c89ca77-26a9-4ef9-87fe-88555431a174.png)

probably that's why I can't find the option to make an ownership change
![screenshot](https://user-images.githubusercontent.com/85469891/184877584-43b69fc5-6329-439d-b680-3f21d7bf6086.png)

**Comment by twan-dev** [comment]
Other things I've tried:
- The tool icon at the lower left corner provides the same menu of options, - The pencil allows me to edit the post but not the ownership
- The tool icon on the left to the "reply" icon prompts me to add a staff note

**Comment by SirAh0** [comment]
You have to click Select Posts... 
![image](https://user-images.githubusercontent.com/12703396/184886411-f7374618-2264-4aad-9f4c-6e601eec556e.png)

![image](https://user-images.githubusercontent.com/12703396/184886357-a76ce01b-bf1d-4b64-bc28-e6714fb3873f.png)

![image](https://user-images.githubusercontent.com/12703396/184886378-75dd0018-ea14-422f-a8b8-18fd0a89ad4d.png)

**Comment by twan-dev** [comment]
![Screenshot](https://user-images.githubusercontent.com/85469891/184886860-829eebfc-3fcb-4f92-9a82-37f6fe842e9b.png)

**Comment by SirAh0** [comment]
darn

**Comment by SirAh0** [comment]
Moderators can now change ownership. @twan-dev has a working solution and we will integrate to project plan, closing issue.
