### ISSUE TITLE
🧰 - Sourcecred Setup

### ISSUE THREAD

**Issue by twan-dev** [smartcontractresearchforum/IT#90]
### General Issue

I get this error

```
Error: EACCES: permission denied, mkdir 'site'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command
```

When I run 
```
yarn sourcecred serve
```

I'm at this step
![0827sc](https://user-images.githubusercontent.com/85469891/187017879-0d62a163-15a6-4e70-83f1-7a74c0f3fb3a.png)

I'm in a MacOS

**Comment by twan-dev** [comment]
Solved with `sudo`

**Comment by SirAh0** [comment]
yay sudo!
