### ISSUE TITLE
Seshbot Needs Manage Events

### ISSUE THREAD

**Issue by SirAh0** [smartcontractresearchforum/IT#92]
**Role**
`Sesh`

**Permission**
`Manage Events`

![image](https://user-images.githubusercontent.com/12703396/187230916-802ab403-0dd3-4d08-b1aa-ba0cde4fc52a.png)

Seshbot added a feature to handle Native Discord events but to do so needs the `Manage Events` permission.

![image](https://user-images.githubusercontent.com/12703396/187230683-116b690a-3aa1-49c1-98c0-4a3f1b4f6080.png)

**Comment by ghettodev** [comment]
Permission added.

**Comment by SirAh0** [comment]
Thanks!
